---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ["base"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: dotfiles, tags: ["dotfiles"] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
